; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=armv7-unknown-linux-gnueabihf -verify-machineinstrs < %s | FileCheck %s --check-prefix=ARM
; RUN: llc -mtriple=thumbv7-unknown-linux-gnueabihf -verify-machineinstrs < %s | FileCheck %s --check-prefix=THUMB

declare void @llvm.experimental.patchpoint.void(i64, i32, ptr, i32, ...)
declare i32 @llvm.experimental.patchpoint.i32(i64, i32, ptr, i32, ...)
declare ptr @llvm.experimental.patchpoint.p0(i64, i32, ptr, i32, ...)
declare float @llvm.experimental.patchpoint.f32(i64, i32, ptr, i32, ...)

declare i32 @foo(i32, i32)

; Test small patchpoints that don't emit calls.
define void @small_patchpoint_codegen(i32 %p1, i32 %p2) {
; ARM-LABEL: small_patchpoint_codegen:
; ARM:       @ %bb.0: @ %entry
; ARM-NEXT:    .save {r11, lr}
; ARM-NEXT:    push {r11, lr}
; ARM-NEXT:    .setfp r11, sp
; ARM-NEXT:    mov r11, sp
; ARM-NEXT:  .Ltmp0:
; ARM-NEXT:    nop
; ARM-NEXT:    nop
; ARM-NEXT:    nop
; ARM-NEXT:    pop {r11, pc}
;
; THUMB-LABEL: small_patchpoint_codegen:
; THUMB:       @ %bb.0: @ %entry
; THUMB-NEXT:    .save {r7, lr}
; THUMB-NEXT:    push {r7, lr}
; THUMB-NEXT:    .setfp r7, sp
; THUMB-NEXT:    mov r7, sp
; THUMB-NEXT:  .Ltmp0:
; THUMB-NEXT:    nop
; THUMB-NEXT:    nop
; THUMB-NEXT:    nop
; THUMB-NEXT:    nop
; THUMB-NEXT:    nop
; THUMB-NEXT:    nop
; THUMB-NEXT:    pop {r7, pc}
entry:
  tail call void (i64, i32, ptr, i32, ...) @llvm.experimental.patchpoint.void(i64 5, i32 12, ptr null, i32 2, i32 %p1, i32 %p2)
  ret void
}

; Trivial patchpoint codegen for immediate call
define i32 @trivial_patchpoint_codegen(i32 %p1, i32 %p2) {
; ARM-LABEL: trivial_patchpoint_codegen:
; ARM:       @ %bb.0: @ %entry
; ARM-NEXT:    .save {r4, r5, r11, lr}
; ARM-NEXT:    push {r4, r5, r11, lr}
; ARM-NEXT:    .setfp r11, sp, #8
; ARM-NEXT:    add r11, sp, #8
; ARM-NEXT:    mov r4, r0
; ARM-NEXT:  .Ltmp1:
; ARM-NEXT:    movw r12, #48879
; ARM-NEXT:    movt r12, #57005
; ARM-NEXT:    blx r12
; ARM-NEXT:    nop
; ARM-NEXT:    nop
; ARM-NEXT:    mov r5, r0
; ARM-NEXT:    mov r0, r4
; ARM-NEXT:    mov r1, r5
; ARM-NEXT:  .Ltmp2:
; ARM-NEXT:    movw r12, #48878
; ARM-NEXT:    movt r12, #57005
; ARM-NEXT:    blx r12
; ARM-NEXT:    nop
; ARM-NEXT:    nop
; ARM-NEXT:    mov r0, r5
; ARM-NEXT:    pop {r4, r5, r11, pc}
;
; THUMB-LABEL: trivial_patchpoint_codegen:
; THUMB:       @ %bb.0: @ %entry
; THUMB-NEXT:    .save {r4, r5, r7, lr}
; THUMB-NEXT:    push {r4, r5, r7, lr}
; THUMB-NEXT:    .setfp r7, sp, #8
; THUMB-NEXT:    add r7, sp, #8
; THUMB-NEXT:    mov r4, r0
; THUMB-NEXT:  .Ltmp1:
; THUMB-NEXT:    movw r12, #48879
; THUMB-NEXT:    movt r12, #57005
; THUMB-NEXT:    blx r12
; THUMB-NEXT:    nop
; THUMB-NEXT:    nop
; THUMB-NEXT:    nop
; THUMB-NEXT:    nop
; THUMB-NEXT:    nop
; THUMB-NEXT:    mov r5, r0
; THUMB-NEXT:    mov r0, r4
; THUMB-NEXT:    mov r1, r5
; THUMB-NEXT:  .Ltmp2:
; THUMB-NEXT:    movw r12, #48878
; THUMB-NEXT:    movt r12, #57005
; THUMB-NEXT:    blx r12
; THUMB-NEXT:    nop
; THUMB-NEXT:    nop
; THUMB-NEXT:    nop
; THUMB-NEXT:    nop
; THUMB-NEXT:    nop
; THUMB-NEXT:    mov r0, r5
; THUMB-NEXT:    pop {r4, r5, r7, pc}
entry:
  %resolveCall2 = inttoptr i32 -559038737 to ptr
  %result = tail call i32 (i64, i32, ptr, i32, ...) @llvm.experimental.patchpoint.i32(i64 2, i32 20, ptr %resolveCall2, i32 2, i32 %p1, i32 %p2)
  %resolveCall3 = inttoptr i32 -559038738 to ptr
  tail call void (i64, i32, ptr, i32, ...) @llvm.experimental.patchpoint.void(i64 3, i32 20, ptr %resolveCall3, i32 2, i32 %p1, i32 %result)
  ret i32 %result
}

; Trivial symbolic patchpoint codegen for symbolic target
define i32 @trivial_symbolic_patchpoint_codegen(i32 %p1, i32 %p2) {
; ARM-LABEL: trivial_symbolic_patchpoint_codegen:
; ARM:       @ %bb.0: @ %entry
; ARM-NEXT:    .save {r11, lr}
; ARM-NEXT:    push {r11, lr}
; ARM-NEXT:    .setfp r11, sp
; ARM-NEXT:    mov r11, sp
; ARM-NEXT:  .Ltmp3:
; ARM-NEXT:    bl foo
; ARM-NEXT:    nop
; ARM-NEXT:    nop
; ARM-NEXT:    pop {r11, pc}
;
; THUMB-LABEL: trivial_symbolic_patchpoint_codegen:
; THUMB:       @ %bb.0: @ %entry
; THUMB-NEXT:    .save {r7, lr}
; THUMB-NEXT:    push {r7, lr}
; THUMB-NEXT:    .setfp r7, sp
; THUMB-NEXT:    mov r7, sp
; THUMB-NEXT:  .Ltmp3:
; THUMB-NEXT:    bl foo
; THUMB-NEXT:    nop
; THUMB-NEXT:    nop
; THUMB-NEXT:    nop
; THUMB-NEXT:    nop
; THUMB-NEXT:    pop {r7, pc}
entry:
  %result = tail call i32 (i64, i32, ptr, i32, ...) @llvm.experimental.patchpoint.i32(i64 9, i32 12, ptr @foo, i32 2, i32 %p1, i32 %p2)
  ret i32 %result
}

; A shadow exactly the size of the encoded call needs no padding
define void @exact_shadow_symbolic(i32 %p1) {
; ARM-LABEL: exact_shadow_symbolic:
; ARM:       @ %bb.0: @ %entry
; ARM-NEXT:    .save {r11, lr}
; ARM-NEXT:    push {r11, lr}
; ARM-NEXT:    .setfp r11, sp
; ARM-NEXT:    mov r11, sp
; ARM-NEXT:  .Ltmp4:
; ARM-NEXT:    bl foo
; ARM-NEXT:    pop {r11, pc}
;
; THUMB-LABEL: exact_shadow_symbolic:
; THUMB:       @ %bb.0: @ %entry
; THUMB-NEXT:    .save {r7, lr}
; THUMB-NEXT:    push {r7, lr}
; THUMB-NEXT:    .setfp r7, sp
; THUMB-NEXT:    mov r7, sp
; THUMB-NEXT:  .Ltmp4:
; THUMB-NEXT:    bl foo
; THUMB-NEXT:    pop {r7, pc}
entry:
  tail call void (i64, i32, ptr, i32, ...) @llvm.experimental.patchpoint.void(i64 10, i32 4, ptr @foo, i32 1, i32 %p1)
  ret void
}

; A shadow exactly the size of the encoded call needs no padding
define void @exact_shadow_immediate(i32 %p1) {
; ARM-LABEL: exact_shadow_immediate:
; ARM:       @ %bb.0: @ %entry
; ARM-NEXT:    .save {r11, lr}
; ARM-NEXT:    push {r11, lr}
; ARM-NEXT:    .setfp r11, sp
; ARM-NEXT:    mov r11, sp
; ARM-NEXT:  .Ltmp5:
; ARM-NEXT:    movw r12, #43981
; ARM-NEXT:    movt r12, #4660
; ARM-NEXT:    blx r12
; ARM-NEXT:    pop {r11, pc}
;
; THUMB-LABEL: exact_shadow_immediate:
; THUMB:       @ %bb.0: @ %entry
; THUMB-NEXT:    .save {r7, lr}
; THUMB-NEXT:    push {r7, lr}
; THUMB-NEXT:    .setfp r7, sp
; THUMB-NEXT:    mov r7, sp
; THUMB-NEXT:  .Ltmp5:
; THUMB-NEXT:    movw r12, #43981
; THUMB-NEXT:    movt r12, #4660
; THUMB-NEXT:    blx r12
; THUMB-NEXT:    nop
; THUMB-NEXT:    pop {r7, pc}
entry:
  %target = inttoptr i32 305441741 to ptr
  tail call void (i64, i32, ptr, i32, ...) @llvm.experimental.patchpoint.void(i64 11, i32 12, ptr %target, i32 1, i32 %p1)
  ret void
}

; Test register allocation for an i32 result value of patchpoint.
define i32 @generic_patchpoint_i32() {
; ARM-LABEL: generic_patchpoint_i32:
; ARM:       @ %bb.0: @ %entry
; ARM-NEXT:    .save {r11, lr}
; ARM-NEXT:    push {r11, lr}
; ARM-NEXT:    .setfp r11, sp
; ARM-NEXT:    mov r11, sp
; ARM-NEXT:  .Ltmp6:
; ARM-NEXT:    nop
; ARM-NEXT:    pop {r11, pc}
;
; THUMB-LABEL: generic_patchpoint_i32:
; THUMB:       @ %bb.0: @ %entry
; THUMB-NEXT:    .save {r7, lr}
; THUMB-NEXT:    push {r7, lr}
; THUMB-NEXT:    .setfp r7, sp
; THUMB-NEXT:    mov r7, sp
; THUMB-NEXT:  .Ltmp6:
; THUMB-NEXT:    nop
; THUMB-NEXT:    nop
; THUMB-NEXT:    pop {r7, pc}
entry:
  %result = tail call i32 (i64, i32, ptr, i32, ...) @llvm.experimental.patchpoint.i32(i64 5, i32 4, ptr null, i32 0)
  ret i32 %result
}

; Test register allocation for a ptr result value of patchpoint.
define ptr @generic_patchpoint_p0() {
; ARM-LABEL: generic_patchpoint_p0:
; ARM:       @ %bb.0: @ %entry
; ARM-NEXT:    .save {r11, lr}
; ARM-NEXT:    push {r11, lr}
; ARM-NEXT:    .setfp r11, sp
; ARM-NEXT:    mov r11, sp
; ARM-NEXT:  .Ltmp7:
; ARM-NEXT:    nop
; ARM-NEXT:    pop {r11, pc}
;
; THUMB-LABEL: generic_patchpoint_p0:
; THUMB:       @ %bb.0: @ %entry
; THUMB-NEXT:    .save {r7, lr}
; THUMB-NEXT:    push {r7, lr}
; THUMB-NEXT:    .setfp r7, sp
; THUMB-NEXT:    mov r7, sp
; THUMB-NEXT:  .Ltmp7:
; THUMB-NEXT:    nop
; THUMB-NEXT:    nop
; THUMB-NEXT:    pop {r7, pc}
entry:
  %result = tail call ptr (i64, i32, ptr, i32, ...) @llvm.experimental.patchpoint.p0(i64 5, i32 4, ptr null, i32 0)
  ret ptr %result
}

; Test register allocation for a float result value of patchpoint.
define float @generic_patchpoint_f32() {
; ARM-LABEL: generic_patchpoint_f32:
; ARM:       @ %bb.0: @ %entry
; ARM-NEXT:    .save {r11, lr}
; ARM-NEXT:    push {r11, lr}
; ARM-NEXT:    .setfp r11, sp
; ARM-NEXT:    mov r11, sp
; ARM-NEXT:  .Ltmp8:
; ARM-NEXT:    nop
; ARM-NEXT:    pop {r11, pc}
;
; THUMB-LABEL: generic_patchpoint_f32:
; THUMB:       @ %bb.0: @ %entry
; THUMB-NEXT:    .save {r7, lr}
; THUMB-NEXT:    push {r7, lr}
; THUMB-NEXT:    .setfp r7, sp
; THUMB-NEXT:    mov r7, sp
; THUMB-NEXT:  .Ltmp8:
; THUMB-NEXT:    nop
; THUMB-NEXT:    nop
; THUMB-NEXT:    pop {r7, pc}
entry:
  %result = tail call float (i64, i32, ptr, i32, ...) @llvm.experimental.patchpoint.f32(i64 5, i32 4, ptr null, i32 0)
  ret float %result
}

; A target address with bit 31 set reaches the AsmPrinter sign-extended
define i32 @high_target_address_patchpoint_codegen() {
; ARM-LABEL: high_target_address_patchpoint_codegen:
; ARM:       @ %bb.0: @ %entry
; ARM-NEXT:    .save {r11, lr}
; ARM-NEXT:    push {r11, lr}
; ARM-NEXT:    .setfp r11, sp
; ARM-NEXT:    mov r11, sp
; ARM-NEXT:  .Ltmp9:
; ARM-NEXT:    movw r12, #0
; ARM-NEXT:    movt r12, #32768
; ARM-NEXT:    blx r12
; ARM-NEXT:    nop
; ARM-NEXT:    nop
; ARM-NEXT:    pop {r11, pc}
;
; THUMB-LABEL: high_target_address_patchpoint_codegen:
; THUMB:       @ %bb.0: @ %entry
; THUMB-NEXT:    .save {r7, lr}
; THUMB-NEXT:    push {r7, lr}
; THUMB-NEXT:    .setfp r7, sp
; THUMB-NEXT:    mov r7, sp
; THUMB-NEXT:  .Ltmp9:
; THUMB-NEXT:    movw r12, #0
; THUMB-NEXT:    movt r12, #32768
; THUMB-NEXT:    blx r12
; THUMB-NEXT:    nop
; THUMB-NEXT:    nop
; THUMB-NEXT:    nop
; THUMB-NEXT:    nop
; THUMB-NEXT:    nop
; THUMB-NEXT:    pop {r7, pc}
entry:
  %target = inttoptr i32 -2147483648 to ptr
  %result = tail call i32 (i64, i32, ptr, i32, ...) @llvm.experimental.patchpoint.i32(i64 12, i32 20, ptr %target, i32 0)
  ret i32 %result
}
