; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=armv7-unknown-linux-gnueabihf -verify-machineinstrs < %s | FileCheck %s --check-prefix=NORESERVE
; RUN: llc -mtriple=armv7-unknown-linux-gnueabihf -mattr=+reserve-r10 -verify-machineinstrs < %s | FileCheck %s --check-prefix=RESERVE
; RUN: llc -mtriple=armv7-unknown-linux-gnueabihf -mattr=+reserve-r9,+reserve-r10 -verify-machineinstrs < %s | FileCheck %s --check-prefix=RESERVE-BOTH

@g = external global [16 x i32]

declare void @sink(i32)

; Twelve values are alive, r10 must not be used
define void @pressure() {
; NORESERVE-LABEL: pressure:
; NORESERVE:       @ %bb.0:
; NORESERVE-NEXT:    .save {r4, r5, r6, r7, r8, r9, r10, lr}
; NORESERVE-NEXT:    push {r4, r5, r6, r7, r8, r9, r10, lr}
; NORESERVE-NEXT:    movw r0, :lower16:g
; NORESERVE-NEXT:    movt r0, :upper16:g
; NORESERVE-NEXT:    ldr r1, [r0]
; NORESERVE-NEXT:    ldr r2, [r0, #4]
; NORESERVE-NEXT:    ldr r3, [r0, #8]
; NORESERVE-NEXT:    ldr r12, [r0, #12]
; NORESERVE-NEXT:    ldr lr, [r0, #16]
; NORESERVE-NEXT:    ldr r4, [r0, #20]
; NORESERVE-NEXT:    ldr r5, [r0, #24]
; NORESERVE-NEXT:    ldr r6, [r0, #28]
; NORESERVE-NEXT:    ldr r7, [r0, #32]
; NORESERVE-NEXT:    ldr r8, [r0, #36]
; NORESERVE-NEXT:    ldr r9, [r0, #40]
; NORESERVE-NEXT:    ldr r10, [r0, #44]
; NORESERVE-NEXT:    str r1, [r0, #44]
; NORESERVE-NEXT:    str r2, [r0, #40]
; NORESERVE-NEXT:    str r3, [r0, #36]
; NORESERVE-NEXT:    str r12, [r0, #32]
; NORESERVE-NEXT:    str lr, [r0, #28]
; NORESERVE-NEXT:    str r4, [r0, #24]
; NORESERVE-NEXT:    str r5, [r0, #20]
; NORESERVE-NEXT:    str r6, [r0, #16]
; NORESERVE-NEXT:    str r7, [r0, #12]
; NORESERVE-NEXT:    str r8, [r0, #8]
; NORESERVE-NEXT:    str r9, [r0, #4]
; NORESERVE-NEXT:    str r10, [r0]
; NORESERVE-NEXT:    pop {r4, r5, r6, r7, r8, r9, r10, pc}
;
; RESERVE-LABEL: pressure:
; RESERVE:       @ %bb.0:
; RESERVE-NEXT:    .save {r4, r5, r6, r7, r8, r9, r11, lr}
; RESERVE-NEXT:    push {r4, r5, r6, r7, r8, r9, r11, lr}
; RESERVE-NEXT:    movw r0, :lower16:g
; RESERVE-NEXT:    movt r0, :upper16:g
; RESERVE-NEXT:    ldr r1, [r0]
; RESERVE-NEXT:    ldr r2, [r0, #4]
; RESERVE-NEXT:    ldr r3, [r0, #8]
; RESERVE-NEXT:    ldr r12, [r0, #12]
; RESERVE-NEXT:    ldr lr, [r0, #16]
; RESERVE-NEXT:    ldr r4, [r0, #20]
; RESERVE-NEXT:    ldr r5, [r0, #24]
; RESERVE-NEXT:    ldr r6, [r0, #28]
; RESERVE-NEXT:    ldr r7, [r0, #32]
; RESERVE-NEXT:    ldr r8, [r0, #36]
; RESERVE-NEXT:    ldr r9, [r0, #40]
; RESERVE-NEXT:    ldr r11, [r0, #44]
; RESERVE-NEXT:    str r1, [r0, #44]
; RESERVE-NEXT:    str r2, [r0, #40]
; RESERVE-NEXT:    str r3, [r0, #36]
; RESERVE-NEXT:    str r12, [r0, #32]
; RESERVE-NEXT:    str lr, [r0, #28]
; RESERVE-NEXT:    str r4, [r0, #24]
; RESERVE-NEXT:    str r5, [r0, #20]
; RESERVE-NEXT:    str r6, [r0, #16]
; RESERVE-NEXT:    str r7, [r0, #12]
; RESERVE-NEXT:    str r8, [r0, #8]
; RESERVE-NEXT:    str r9, [r0, #4]
; RESERVE-NEXT:    str r11, [r0]
; RESERVE-NEXT:    pop {r4, r5, r6, r7, r8, r9, r11, pc}
;
; RESERVE-BOTH-LABEL: pressure:
; RESERVE-BOTH:       @ %bb.0:
; RESERVE-BOTH-NEXT:    .save {r4, r5, r6, r7, r8, r11, lr}
; RESERVE-BOTH-NEXT:    push {r4, r5, r6, r7, r8, r11, lr}
; RESERVE-BOTH-NEXT:    .pad #8
; RESERVE-BOTH-NEXT:    sub sp, sp, #8
; RESERVE-BOTH-NEXT:    movw r0, :lower16:g
; RESERVE-BOTH-NEXT:    movt r0, :upper16:g
; RESERVE-BOTH-NEXT:    ldr r1, [r0]
; RESERVE-BOTH-NEXT:    str r1, [sp] @ 4-byte Spill
; RESERVE-BOTH-NEXT:    ldr r2, [r0, #4]
; RESERVE-BOTH-NEXT:    ldr r3, [r0, #8]
; RESERVE-BOTH-NEXT:    ldr r12, [r0, #12]
; RESERVE-BOTH-NEXT:    ldr lr, [r0, #16]
; RESERVE-BOTH-NEXT:    ldr r4, [r0, #20]
; RESERVE-BOTH-NEXT:    ldr r5, [r0, #24]
; RESERVE-BOTH-NEXT:    ldr r6, [r0, #28]
; RESERVE-BOTH-NEXT:    ldr r7, [r0, #32]
; RESERVE-BOTH-NEXT:    ldr r8, [r0, #36]
; RESERVE-BOTH-NEXT:    ldr r11, [r0, #40]
; RESERVE-BOTH-NEXT:    ldr r1, [r0, #44]
; RESERVE-BOTH-NEXT:    str r1, [sp, #4] @ 4-byte Spill
; RESERVE-BOTH-NEXT:    ldr r1, [sp] @ 4-byte Reload
; RESERVE-BOTH-NEXT:    str r1, [r0, #44]
; RESERVE-BOTH-NEXT:    str r2, [r0, #40]
; RESERVE-BOTH-NEXT:    str r3, [r0, #36]
; RESERVE-BOTH-NEXT:    str r12, [r0, #32]
; RESERVE-BOTH-NEXT:    str lr, [r0, #28]
; RESERVE-BOTH-NEXT:    str r4, [r0, #24]
; RESERVE-BOTH-NEXT:    str r5, [r0, #20]
; RESERVE-BOTH-NEXT:    str r6, [r0, #16]
; RESERVE-BOTH-NEXT:    str r7, [r0, #12]
; RESERVE-BOTH-NEXT:    str r8, [r0, #8]
; RESERVE-BOTH-NEXT:    str r11, [r0, #4]
; RESERVE-BOTH-NEXT:    ldr r1, [sp, #4] @ 4-byte Reload
; RESERVE-BOTH-NEXT:    str r1, [r0]
; RESERVE-BOTH-NEXT:    add sp, sp, #8
; RESERVE-BOTH-NEXT:    pop {r4, r5, r6, r7, r8, r11, pc}
  %p0 = getelementptr [16 x i32], ptr @g, i32 0, i32 0
  %p1 = getelementptr [16 x i32], ptr @g, i32 0, i32 1
  %p2 = getelementptr [16 x i32], ptr @g, i32 0, i32 2
  %p3 = getelementptr [16 x i32], ptr @g, i32 0, i32 3
  %p4 = getelementptr [16 x i32], ptr @g, i32 0, i32 4
  %p5 = getelementptr [16 x i32], ptr @g, i32 0, i32 5
  %p6 = getelementptr [16 x i32], ptr @g, i32 0, i32 6
  %p7 = getelementptr [16 x i32], ptr @g, i32 0, i32 7
  %p8 = getelementptr [16 x i32], ptr @g, i32 0, i32 8
  %p9 = getelementptr [16 x i32], ptr @g, i32 0, i32 9
  %pa = getelementptr [16 x i32], ptr @g, i32 0, i32 10
  %pb = getelementptr [16 x i32], ptr @g, i32 0, i32 11
  %v0 = load volatile i32, ptr %p0
  %v1 = load volatile i32, ptr %p1
  %v2 = load volatile i32, ptr %p2
  %v3 = load volatile i32, ptr %p3
  %v4 = load volatile i32, ptr %p4
  %v5 = load volatile i32, ptr %p5
  %v6 = load volatile i32, ptr %p6
  %v7 = load volatile i32, ptr %p7
  %v8 = load volatile i32, ptr %p8
  %v9 = load volatile i32, ptr %p9
  %va = load volatile i32, ptr %pa
  %vb = load volatile i32, ptr %pb
  store volatile i32 %v0, ptr %pb
  store volatile i32 %v1, ptr %pa
  store volatile i32 %v2, ptr %p9
  store volatile i32 %v3, ptr %p8
  store volatile i32 %v4, ptr %p7
  store volatile i32 %v5, ptr %p6
  store volatile i32 %v6, ptr %p5
  store volatile i32 %v7, ptr %p4
  store volatile i32 %v8, ptr %p3
  store volatile i32 %v9, ptr %p2
  store volatile i32 %va, ptr %p1
  store volatile i32 %vb, ptr %p0
  ret void
}

; If a function clobbers the value (for whatever reason), it still should be saved
define void @explicit_clobber(i32 %v) {
; NORESERVE-LABEL: explicit_clobber:
; NORESERVE:       @ %bb.0:
; NORESERVE-NEXT:    .save {r10, lr}
; NORESERVE-NEXT:    push {r10, lr}
; NORESERVE-NEXT:    @APP
; NORESERVE-NEXT:    mov r10, r0
; NORESERVE-NEXT:    @NO_APP
; NORESERVE-NEXT:    bl sink
; NORESERVE-NEXT:    pop {r10, pc}
;
; RESERVE-LABEL: explicit_clobber:
; RESERVE:       @ %bb.0:
; RESERVE-NEXT:    .save {r10, lr}
; RESERVE-NEXT:    push {r10, lr}
; RESERVE-NEXT:    @APP
; RESERVE-NEXT:    mov r10, r0
; RESERVE-NEXT:    @NO_APP
; RESERVE-NEXT:    bl sink
; RESERVE-NEXT:    pop {r10, pc}
;
; RESERVE-BOTH-LABEL: explicit_clobber:
; RESERVE-BOTH:       @ %bb.0:
; RESERVE-BOTH-NEXT:    .save {r10, lr}
; RESERVE-BOTH-NEXT:    push {r10, lr}
; RESERVE-BOTH-NEXT:    @APP
; RESERVE-BOTH-NEXT:    mov r10, r0
; RESERVE-BOTH-NEXT:    @NO_APP
; RESERVE-BOTH-NEXT:    bl sink
; RESERVE-BOTH-NEXT:    pop {r10, pc}
  call void asm sideeffect "mov r10, $0", "r,~{r10}"(i32 %v)
  call void @sink(i32 %v)
  ret void
}

; Three GPR saves is odd, so one more callee-saved GPR is spilled as padding. The order is r10->r9->r8
define void @odd_pad(i32 %v) {
; NORESERVE-LABEL: odd_pad:
; NORESERVE:       @ %bb.0:
; NORESERVE-NEXT:    .save {r4, r10, r11, lr}
; NORESERVE-NEXT:    push {r4, r10, r11, lr}
; NORESERVE-NEXT:    @APP
; NORESERVE-NEXT:    @NO_APP
; NORESERVE-NEXT:    bl sink
; NORESERVE-NEXT:    pop {r4, r10, r11, pc}
;
; RESERVE-LABEL: odd_pad:
; RESERVE:       @ %bb.0:
; RESERVE-NEXT:    .save {r4, r9, r11, lr}
; RESERVE-NEXT:    push {r4, r9, r11, lr}
; RESERVE-NEXT:    @APP
; RESERVE-NEXT:    @NO_APP
; RESERVE-NEXT:    bl sink
; RESERVE-NEXT:    pop {r4, r9, r11, pc}
;
; RESERVE-BOTH-LABEL: odd_pad:
; RESERVE-BOTH:       @ %bb.0:
; RESERVE-BOTH-NEXT:    .save {r4, r8, r11, lr}
; RESERVE-BOTH-NEXT:    push {r4, r8, r11, lr}
; RESERVE-BOTH-NEXT:    @APP
; RESERVE-BOTH-NEXT:    @NO_APP
; RESERVE-BOTH-NEXT:    bl sink
; RESERVE-BOTH-NEXT:    pop {r4, r8, r11, pc}
  call void asm sideeffect "", "~{r4},~{r11}"()
  call void @sink(i32 %v)
  ret void
}

; Three GPR saves is odd, so padding is needed. Without r9, r10, no register is available, and it needs to pad via stack subtract
define void @no_pad_candidate(i32 %v) {
; NORESERVE-LABEL: no_pad_candidate:
; NORESERVE:       @ %bb.0:
; NORESERVE-NEXT:    .save {r4, r5, r6, r7, r8, r10, r11, lr}
; NORESERVE-NEXT:    push {r4, r5, r6, r7, r8, r10, r11, lr}
; NORESERVE-NEXT:    .vsave {d8}
; NORESERVE-NEXT:    vpush {d8}
; NORESERVE-NEXT:    @APP
; NORESERVE-NEXT:    @NO_APP
; NORESERVE-NEXT:    bl sink
; NORESERVE-NEXT:    vpop {d8}
; NORESERVE-NEXT:    pop {r4, r5, r6, r7, r8, r10, r11, pc}
;
; RESERVE-LABEL: no_pad_candidate:
; RESERVE:       @ %bb.0:
; RESERVE-NEXT:    .save {r4, r5, r6, r7, r8, r9, r11, lr}
; RESERVE-NEXT:    push {r4, r5, r6, r7, r8, r9, r11, lr}
; RESERVE-NEXT:    .vsave {d8}
; RESERVE-NEXT:    vpush {d8}
; RESERVE-NEXT:    @APP
; RESERVE-NEXT:    @NO_APP
; RESERVE-NEXT:    bl sink
; RESERVE-NEXT:    vpop {d8}
; RESERVE-NEXT:    pop {r4, r5, r6, r7, r8, r9, r11, pc}
;
; RESERVE-BOTH-LABEL: no_pad_candidate:
; RESERVE-BOTH:       @ %bb.0:
; RESERVE-BOTH-NEXT:    .save {r4, r5, r6, r7, r8, r11, lr}
; RESERVE-BOTH-NEXT:    push {r4, r5, r6, r7, r8, r11, lr}
; RESERVE-BOTH-NEXT:    .pad #4
; RESERVE-BOTH-NEXT:    sub sp, sp, #4
; RESERVE-BOTH-NEXT:    .vsave {d8}
; RESERVE-BOTH-NEXT:    vpush {d8}
; RESERVE-BOTH-NEXT:    @APP
; RESERVE-BOTH-NEXT:    @NO_APP
; RESERVE-BOTH-NEXT:    bl sink
; RESERVE-BOTH-NEXT:    vpop {d8}
; RESERVE-BOTH-NEXT:    add sp, sp, #4
; RESERVE-BOTH-NEXT:    pop {r4, r5, r6, r7, r8, r11, pc}
  call void asm sideeffect "", "~{r4},~{r5},~{r6},~{r7},~{r8},~{r11},~{d8}"()
  call void @sink(i32 %v)
  ret void
}
