; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=armv7-unknown-linux-gnueabihf -verify-machineinstrs < %s \
; RUN:   | FileCheck %s --check-prefix=ARM
; RUN: llc -mtriple=armv7-unknown-linux-gnueabihf -mattr=+reserve-r9 \
; RUN:   -verify-machineinstrs < %s | FileCheck %s --check-prefix=ARM-R9
; RUN: llc -mtriple=thumbv7-unknown-linux-gnueabihf -verify-machineinstrs < %s \
; RUN:   | FileCheck %s --check-prefix=THUMB
; RUN: llc -mtriple=thumbv7-unknown-linux-gnueabihf -mattr=+reserve-r9 \
; RUN:   -verify-machineinstrs < %s | FileCheck %s --check-prefix=THUMB-R9

declare void @sink(i32)

define void @cs1_pad(i32 %v) {
; ARM-LABEL: cs1_pad:
; ARM:       @ %bb.0:
; ARM-NEXT:    .save {r4, r5, r9, r10, r11, lr}
; ARM-NEXT:    push {r4, r5, r9, r10, r11, lr}
; ARM-NEXT:    @APP
; ARM-NEXT:    @NO_APP
; ARM-NEXT:    bl sink
; ARM-NEXT:    pop {r4, r5, r9, r10, r11, pc}
;
; ARM-R9-LABEL: cs1_pad:
; ARM-R9:       @ %bb.0:
; ARM-R9-NEXT:    .save {r4, r5, r8, r10, r11, lr}
; ARM-R9-NEXT:    push {r4, r5, r8, r10, r11, lr}
; ARM-R9-NEXT:    @APP
; ARM-R9-NEXT:    @NO_APP
; ARM-R9-NEXT:    bl sink
; ARM-R9-NEXT:    pop {r4, r5, r8, r10, r11, pc}
;
; THUMB-LABEL: cs1_pad:
; THUMB:       @ %bb.0:
; THUMB-NEXT:    .save {r4, r5, r7, r10, r11, lr}
; THUMB-NEXT:    push.w {r4, r5, r7, r10, r11, lr}
; THUMB-NEXT:    @APP
; THUMB-NEXT:    @NO_APP
; THUMB-NEXT:    bl sink
; THUMB-NEXT:    pop.w {r4, r5, r7, r10, r11, pc}
;
; THUMB-R9-LABEL: cs1_pad:
; THUMB-R9:       @ %bb.0:
; THUMB-R9-NEXT:    .save {r4, r5, r7, r10, r11, lr}
; THUMB-R9-NEXT:    push.w {r4, r5, r7, r10, r11, lr}
; THUMB-R9-NEXT:    @APP
; THUMB-R9-NEXT:    @NO_APP
; THUMB-R9-NEXT:    bl sink
; THUMB-R9-NEXT:    pop.w {r4, r5, r7, r10, r11, pc}
  call void asm sideeffect "", "~{r4},~{r5},~{r10},~{r11}"()
  call void @sink(i32 %v)
  ret void
}

define void @cs2_pad(i32 %v) "frame-pointer"="all" {
; ARM-LABEL: cs2_pad:
; ARM:       @ %bb.0:
; ARM-NEXT:    .save {r4, r5, r6, r9, r10, r11, lr}
; ARM-NEXT:    push {r4, r5, r6, r9, r10, r11, lr}
; ARM-NEXT:    .setfp r11, sp, #20
; ARM-NEXT:    add r11, sp, #20
; ARM-NEXT:    .pad #4
; ARM-NEXT:    sub sp, sp, #4
; ARM-NEXT:    @APP
; ARM-NEXT:    @NO_APP
; ARM-NEXT:    bl sink
; ARM-NEXT:    sub sp, r11, #20
; ARM-NEXT:    pop {r4, r5, r6, r9, r10, r11, pc}
;
; ARM-R9-LABEL: cs2_pad:
; ARM-R9:       @ %bb.0:
; ARM-R9-NEXT:    .save {r4, r5, r6, r8, r10, r11, lr}
; ARM-R9-NEXT:    push {r4, r5, r6, r8, r10, r11, lr}
; ARM-R9-NEXT:    .setfp r11, sp, #20
; ARM-R9-NEXT:    add r11, sp, #20
; ARM-R9-NEXT:    .pad #4
; ARM-R9-NEXT:    sub sp, sp, #4
; ARM-R9-NEXT:    @APP
; ARM-R9-NEXT:    @NO_APP
; ARM-R9-NEXT:    bl sink
; ARM-R9-NEXT:    sub sp, r11, #20
; ARM-R9-NEXT:    pop {r4, r5, r6, r8, r10, r11, pc}
;
; THUMB-LABEL: cs2_pad:
; THUMB:       @ %bb.0:
; THUMB-NEXT:    .save {r4, r5, r6, r7, lr}
; THUMB-NEXT:    push {r4, r5, r6, r7, lr}
; THUMB-NEXT:    .setfp r7, sp, #12
; THUMB-NEXT:    add r7, sp, #12
; THUMB-NEXT:    .save {r9, r10, r11}
; THUMB-NEXT:    push.w {r9, r10, r11}
; THUMB-NEXT:    @APP
; THUMB-NEXT:    @NO_APP
; THUMB-NEXT:    bl sink
; THUMB-NEXT:    pop.w {r9, r10, r11}
; THUMB-NEXT:    pop {r4, r5, r6, r7, pc}
;
; THUMB-R9-LABEL: cs2_pad:
; THUMB-R9:       @ %bb.0:
; THUMB-R9-NEXT:    .save {r4, r5, r6, r7, lr}
; THUMB-R9-NEXT:    push {r4, r5, r6, r7, lr}
; THUMB-R9-NEXT:    .setfp r7, sp, #12
; THUMB-R9-NEXT:    add r7, sp, #12
; THUMB-R9-NEXT:    .save {r8, r10, r11}
; THUMB-R9-NEXT:    push.w {r8, r10, r11}
; THUMB-R9-NEXT:    @APP
; THUMB-R9-NEXT:    @NO_APP
; THUMB-R9-NEXT:    bl sink
; THUMB-R9-NEXT:    pop.w {r8, r10, r11}
; THUMB-R9-NEXT:    pop {r4, r5, r6, r7, pc}
  call void asm sideeffect "", "~{r4},~{r5},~{r6},~{r10},~{r11}"()
  call void @sink(i32 %v)
  ret void
}
