; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -verify-machineinstrs < %s | FileCheck %s --check-prefix=ARM
; RUN: llc -mtriple=thumbv7-unknown-linux-gnueabihf -verify-machineinstrs < %s | FileCheck %s --check-prefix=THUMB
; A collection of basic functionality tests for statepoint lowering - most
; interesting cornercases are exercised through the x86 tests.

target datalayout = "e-m:e-p:32:32-Fi8-i64:64-v128:64:128-a:0:32-n32-S64"
target triple = "armv7-unknown-linux-gnueabihf"

%struct = type { i64, i64 }

declare zeroext i1 @return_i1()
declare zeroext i32 @return_i32()
declare ptr @return_i32ptr()
declare float @return_float()
declare double @return_double()
declare %struct @return_struct()
declare void @varargf(i32, ...)

define i1 @test_i1_return() gc "statepoint-example" {
; This is just checking that a i1 gets lowered normally when there's no extra
; state arguments to the statepoint
; ARM-LABEL: test_i1_return:
; ARM:       @ %bb.0: @ %entry
; ARM-NEXT:    .save {r11, lr}
; ARM-NEXT:    push {r11, lr}
; ARM-NEXT:    bl return_i1
; ARM-NEXT:  .Ltmp0:
; ARM-NEXT:    pop {r11, pc}
;
; THUMB-LABEL: test_i1_return:
; THUMB:       @ %bb.0: @ %entry
; THUMB-NEXT:    .save {r7, lr}
; THUMB-NEXT:    push {r7, lr}
; THUMB-NEXT:    bl return_i1
; THUMB-NEXT:  .Ltmp0:
; THUMB-NEXT:    pop {r7, pc}
entry:
  %safepoint_token = tail call token (i64, i32, ptr, i32, i32, ...) @llvm.experimental.gc.statepoint.p0(i64 0, i32 0, ptr elementtype(i1 ()) @return_i1, i32 0, i32 0, i32 0, i32 0)
  %call1 = call zeroext i1 @llvm.experimental.gc.result.i1(token %safepoint_token)
  ret i1 %call1
}

define i32 @test_i32_return() gc "statepoint-example" {
; ARM-LABEL: test_i32_return:
; ARM:       @ %bb.0: @ %entry
; ARM-NEXT:    .save {r11, lr}
; ARM-NEXT:    push {r11, lr}
; ARM-NEXT:    bl return_i32
; ARM-NEXT:  .Ltmp1:
; ARM-NEXT:    pop {r11, pc}
;
; THUMB-LABEL: test_i32_return:
; THUMB:       @ %bb.0: @ %entry
; THUMB-NEXT:    .save {r7, lr}
; THUMB-NEXT:    push {r7, lr}
; THUMB-NEXT:    bl return_i32
; THUMB-NEXT:  .Ltmp1:
; THUMB-NEXT:    pop {r7, pc}
entry:
  %safepoint_token = tail call token (i64, i32, ptr, i32, i32, ...) @llvm.experimental.gc.statepoint.p0(i64 0, i32 0, ptr elementtype(i32 ()) @return_i32, i32 0, i32 0, i32 0, i32 0)
  %call1 = call zeroext i32 @llvm.experimental.gc.result.i32(token %safepoint_token)
  ret i32 %call1
}

define ptr @test_i32ptr_return() gc "statepoint-example" {
; ARM-LABEL: test_i32ptr_return:
; ARM:       @ %bb.0: @ %entry
; ARM-NEXT:    .save {r11, lr}
; ARM-NEXT:    push {r11, lr}
; ARM-NEXT:    bl return_i32ptr
; ARM-NEXT:  .Ltmp2:
; ARM-NEXT:    pop {r11, pc}
;
; THUMB-LABEL: test_i32ptr_return:
; THUMB:       @ %bb.0: @ %entry
; THUMB-NEXT:    .save {r7, lr}
; THUMB-NEXT:    push {r7, lr}
; THUMB-NEXT:    bl return_i32ptr
; THUMB-NEXT:  .Ltmp2:
; THUMB-NEXT:    pop {r7, pc}
entry:
  %safepoint_token = tail call token (i64, i32, ptr, i32, i32, ...) @llvm.experimental.gc.statepoint.p0(i64 0, i32 0, ptr elementtype(ptr ()) @return_i32ptr, i32 0, i32 0, i32 0, i32 0)
  %call1 = call ptr @llvm.experimental.gc.result.p0(token %safepoint_token)
  ret ptr %call1
}

define float @test_float_return() gc "statepoint-example" {
; ARM-LABEL: test_float_return:
; ARM:       @ %bb.0: @ %entry
; ARM-NEXT:    .save {r11, lr}
; ARM-NEXT:    push {r11, lr}
; ARM-NEXT:    bl return_float
; ARM-NEXT:  .Ltmp3:
; ARM-NEXT:    pop {r11, pc}
;
; THUMB-LABEL: test_float_return:
; THUMB:       @ %bb.0: @ %entry
; THUMB-NEXT:    .save {r7, lr}
; THUMB-NEXT:    push {r7, lr}
; THUMB-NEXT:    bl return_float
; THUMB-NEXT:  .Ltmp3:
; THUMB-NEXT:    pop {r7, pc}
entry:
  %safepoint_token = tail call token (i64, i32, ptr, i32, i32, ...) @llvm.experimental.gc.statepoint.p0(i64 0, i32 0, ptr elementtype(float ()) @return_float, i32 0, i32 0, i32 0, i32 0)
  %call1 = call float @llvm.experimental.gc.result.f32(token %safepoint_token)
  ret float %call1
}

define double @test_double_live() gc "statepoint-example" {
; The hard-float ABI returns doubles in d0 and makes d8-d15 callee-saved
; ARM-LABEL: test_double_live:
; ARM:       @ %bb.0: @ %entry
; ARM-NEXT:    .save {r11, lr}
; ARM-NEXT:    push {r11, lr}
; ARM-NEXT:    .vsave {d8}
; ARM-NEXT:    vpush {d8}
; ARM-NEXT:    .pad #8
; ARM-NEXT:    sub sp, sp, #8
; ARM-NEXT:    bl return_double
; ARM-NEXT:    vorr d8, d0, d0
; ARM-NEXT:    vstr d0, [sp]
; ARM-NEXT:    bl return_double
; ARM-NEXT:  .Ltmp4:
; ARM-NEXT:    vadd.f64 d0, d0, d8
; ARM-NEXT:    add sp, sp, #8
; ARM-NEXT:    vpop {d8}
; ARM-NEXT:    pop {r11, pc}
;
; THUMB-LABEL: test_double_live:
; THUMB:       @ %bb.0: @ %entry
; THUMB-NEXT:    .save {r7, lr}
; THUMB-NEXT:    push {r7, lr}
; THUMB-NEXT:    .vsave {d8}
; THUMB-NEXT:    vpush {d8}
; THUMB-NEXT:    .pad #8
; THUMB-NEXT:    sub sp, #8
; THUMB-NEXT:    bl return_double
; THUMB-NEXT:    vorr d8, d0, d0
; THUMB-NEXT:    vstr d0, [sp]
; THUMB-NEXT:    bl return_double
; THUMB-NEXT:  .Ltmp4:
; THUMB-NEXT:    vadd.f64 d0, d0, d8
; THUMB-NEXT:    add sp, #8
; THUMB-NEXT:    vpop {d8}
; THUMB-NEXT:    pop {r7, pc}
entry:
  %arg = call double @return_double()
  %safepoint_token = call token (i64, i32, ptr, i32, i32, ...) @llvm.experimental.gc.statepoint.p0(i64 0, i32 0, ptr elementtype(double ()) @return_double, i32 0, i32 0, i32 0, i32 0) ["deopt" (double %arg)]
  %call1 = call double @llvm.experimental.gc.result.f64(token %safepoint_token)
  %sum = fadd double %call1, %arg
  ret double %sum
}

define %struct @test_struct_return() gc "statepoint-example" {
; ARM-LABEL: test_struct_return:
; ARM:       @ %bb.0: @ %entry
; ARM-NEXT:    .save {r11, lr}
; ARM-NEXT:    push {r11, lr}
; ARM-NEXT:    bl return_struct
; ARM-NEXT:  .Ltmp5:
; ARM-NEXT:    pop {r11, pc}
;
; THUMB-LABEL: test_struct_return:
; THUMB:       @ %bb.0: @ %entry
; THUMB-NEXT:    .save {r7, lr}
; THUMB-NEXT:    push {r7, lr}
; THUMB-NEXT:    bl return_struct
; THUMB-NEXT:  .Ltmp5:
; THUMB-NEXT:    pop {r7, pc}
entry:
  %safepoint_token = tail call token (i64, i32, ptr, i32, i32, ...) @llvm.experimental.gc.statepoint.p0(i64 0, i32 0, ptr elementtype(%struct ()) @return_struct, i32 0, i32 0, i32 0, i32 0)
  %call1 = call %struct @llvm.experimental.gc.result.struct(token %safepoint_token)
  ret %struct %call1
}

define i1 @test_relocate(ptr addrspace(1) %a) gc "statepoint-example" {
; Check that an ununsed relocate has no code-generation impact
; ARM-LABEL: test_relocate:
; ARM:       @ %bb.0: @ %entry
; ARM-NEXT:    .save {r11, lr}
; ARM-NEXT:    push {r11, lr}
; ARM-NEXT:    .pad #8
; ARM-NEXT:    sub sp, sp, #8
; ARM-NEXT:    str r0, [sp, #4]
; ARM-NEXT:    bl return_i1
; ARM-NEXT:  .Ltmp6:
; ARM-NEXT:    add sp, sp, #8
; ARM-NEXT:    pop {r11, pc}
;
; THUMB-LABEL: test_relocate:
; THUMB:       @ %bb.0: @ %entry
; THUMB-NEXT:    .save {r7, lr}
; THUMB-NEXT:    push {r7, lr}
; THUMB-NEXT:    .pad #8
; THUMB-NEXT:    sub sp, #8
; THUMB-NEXT:    str r0, [sp, #4]
; THUMB-NEXT:    bl return_i1
; THUMB-NEXT:  .Ltmp6:
; THUMB-NEXT:    add sp, #8
; THUMB-NEXT:    pop {r7, pc}
entry:
  %safepoint_token = tail call token (i64, i32, ptr, i32, i32, ...) @llvm.experimental.gc.statepoint.p0(i64 0, i32 0, ptr elementtype(i1 ()) @return_i1, i32 0, i32 0, i32 0, i32 0) ["gc-live" (ptr addrspace(1) %a)]
  %call1 = call ptr addrspace(1) @llvm.experimental.gc.relocate.p1(token %safepoint_token,  i32 0, i32 0)
  %call2 = call zeroext i1 @llvm.experimental.gc.result.i1(token %safepoint_token)
  ret i1 %call2
}

define void @test_void_vararg() gc "statepoint-example" {
; Check a statepoint wrapping a *ptr returning vararg function works
; ARM-LABEL: test_void_vararg:
; ARM:       @ %bb.0: @ %entry
; ARM-NEXT:    .save {r11, lr}
; ARM-NEXT:    push {r11, lr}
; ARM-NEXT:    mov r0, #42
; ARM-NEXT:    mov r1, #43
; ARM-NEXT:    bl varargf
; ARM-NEXT:  .Ltmp7:
; ARM-NEXT:    pop {r11, pc}
;
; THUMB-LABEL: test_void_vararg:
; THUMB:       @ %bb.0: @ %entry
; THUMB-NEXT:    .save {r7, lr}
; THUMB-NEXT:    push {r7, lr}
; THUMB-NEXT:    movs r0, #42
; THUMB-NEXT:    movs r1, #43
; THUMB-NEXT:    bl varargf
; THUMB-NEXT:  .Ltmp7:
; THUMB-NEXT:    pop {r7, pc}
entry:
  %safepoint_token = tail call token (i64, i32, ptr, i32, i32, ...) @llvm.experimental.gc.statepoint.p0(i64 0, i32 0, ptr elementtype(void (i32, ...)) @varargf, i32 2, i32 0, i32 42, i32 43, i32 0, i32 0)
  ;; if we try to use the result from a statepoint wrapping a
  ;; non-void-returning varargf, we will experience a crash.
  ret void
}

define i1 @test_i1_return_patchable() gc "statepoint-example" {
; A patchable variant of test_i1_return
; ARM-LABEL: test_i1_return_patchable:
; ARM:       @ %bb.0: @ %entry
; ARM-NEXT:    .save {r11, lr}
; ARM-NEXT:    push {r11, lr}
; ARM-NEXT:    nop
; ARM-NEXT:  .Ltmp8:
; ARM-NEXT:    pop {r11, pc}
;
; THUMB-LABEL: test_i1_return_patchable:
; THUMB:       @ %bb.0: @ %entry
; THUMB-NEXT:    .save {r7, lr}
; THUMB-NEXT:    push {r7, lr}
; THUMB-NEXT:    nop
; THUMB-NEXT:    nop
; THUMB-NEXT:  .Ltmp8:
; THUMB-NEXT:    pop {r7, pc}
entry:
  %safepoint_token = tail call token (i64, i32, ptr, i32, i32, ...) @llvm.experimental.gc.statepoint.p0(i64 0, i32 4, ptr elementtype(i1 ()) null, i32 0, i32 0, i32 0, i32 0)
  %call1 = call zeroext i1 @llvm.experimental.gc.result.i1(token %safepoint_token)
  ret i1 %call1
}

define void @test_indirect_target(ptr %fn) gc "statepoint-example" {
; An indirect call target is lowered to a BLX. That is 4 bytes in ARM mode and
; 2 bytes in Thumb mode
; ARM-LABEL: test_indirect_target:
; ARM:       @ %bb.0: @ %entry
; ARM-NEXT:    .save {r11, lr}
; ARM-NEXT:    push {r11, lr}
; ARM-NEXT:    blx r0
; ARM-NEXT:  .Ltmp9:
; ARM-NEXT:    pop {r11, pc}
;
; THUMB-LABEL: test_indirect_target:
; THUMB:       @ %bb.0: @ %entry
; THUMB-NEXT:    .save {r7, lr}
; THUMB-NEXT:    push {r7, lr}
; THUMB-NEXT:    blx r0
; THUMB-NEXT:  .Ltmp9:
; THUMB-NEXT:    pop {r7, pc}
entry:
  %safepoint_token = tail call token (i64, i32, ptr, i32, i32, ...) @llvm.experimental.gc.statepoint.p0(i64 0, i32 0, ptr elementtype(void ()) %fn, i32 0, i32 0, i32 0, i32 0)
  ret void
}

declare void @consume(ptr addrspace(1) %obj)

define i1 @test_cross_bb(ptr addrspace(1) %a, i1 %external_cond) gc "statepoint-example" {
; ARM-LABEL: test_cross_bb:
; ARM:       @ %bb.0: @ %entry
; ARM-NEXT:    .save {r4, r5, r6, lr}
; ARM-NEXT:    push {r4, r5, r6, lr}
; ARM-NEXT:    .pad #8
; ARM-NEXT:    sub sp, sp, #8
; ARM-NEXT:    mov r6, r1
; ARM-NEXT:    str r0, [sp, #4]
; ARM-NEXT:    mov r5, #1
; ARM-NEXT:    bl return_i1
; ARM-NEXT:  .Ltmp10:
; ARM-NEXT:    tst r6, #1
; ARM-NEXT:    beq .LBB10_2
; ARM-NEXT:  @ %bb.1: @ %left
; ARM-NEXT:    mov r4, r0
; ARM-NEXT:    ldr r0, [sp, #4]
; ARM-NEXT:    bl consume
; ARM-NEXT:    mov r5, r4
; ARM-NEXT:  .LBB10_2: @ %common.ret
; ARM-NEXT:    mov r0, r5
; ARM-NEXT:    add sp, sp, #8
; ARM-NEXT:    pop {r4, r5, r6, pc}
;
; THUMB-LABEL: test_cross_bb:
; THUMB:       @ %bb.0: @ %entry
; THUMB-NEXT:    .save {r4, lr}
; THUMB-NEXT:    push {r4, lr}
; THUMB-NEXT:    .pad #8
; THUMB-NEXT:    sub sp, #8
; THUMB-NEXT:    str r0, [sp, #4]
; THUMB-NEXT:    lsls r4, r1, #31
; THUMB-NEXT:    bl return_i1
; THUMB-NEXT:  .Ltmp10:
; THUMB-NEXT:    cbz r4, .LBB10_2
; THUMB-NEXT:  @ %bb.1: @ %left
; THUMB-NEXT:    ldr r1, [sp, #4]
; THUMB-NEXT:    mov r4, r0
; THUMB-NEXT:    mov r0, r1
; THUMB-NEXT:    bl consume
; THUMB-NEXT:    mov r0, r4
; THUMB-NEXT:    add sp, #8
; THUMB-NEXT:    pop {r4, pc}
; THUMB-NEXT:  .LBB10_2:
; THUMB-NEXT:    movs r0, #1
; THUMB-NEXT:    add sp, #8
; THUMB-NEXT:    pop {r4, pc}
entry:
  %safepoint_token = tail call token (i64, i32, ptr, i32, i32, ...) @llvm.experimental.gc.statepoint.p0(i64 0, i32 0, ptr elementtype(i1 ()) @return_i1, i32 0, i32 0, i32 0, i32 0) ["gc-live" (ptr addrspace(1) %a)]
  br i1 %external_cond, label %left, label %right

left:
  %call1 = call ptr addrspace(1) @llvm.experimental.gc.relocate.p1(token %safepoint_token,  i32 0, i32 0)
  %call2 = call zeroext i1 @llvm.experimental.gc.result.i1(token %safepoint_token)
  call void @consume(ptr addrspace(1) %call1)
  ret i1 %call2

right:
  ret i1 true
}

%struct2 = type { i64, i64, i64 }

declare void @consume_attributes(i32, ptr nest, i32, ptr byval(%struct2))

define void @test_attributes(ptr byval(%struct2) %s) gc "statepoint-example" {
; ARM-LABEL: test_attributes:
; ARM:       @ %bb.0: @ %entry
; ARM-NEXT:    .pad #16
; ARM-NEXT:    sub sp, sp, #16
; ARM-NEXT:    .save {r11, lr}
; ARM-NEXT:    push {r11, lr}
; ARM-NEXT:    .pad #24
; ARM-NEXT:    sub sp, sp, #24
; ARM-NEXT:    add r12, sp, #32
; ARM-NEXT:    stm r12, {r0, r1, r2, r3}
; ARM-NEXT:    add r0, sp, #32
; ARM-NEXT:    mov r1, sp
; ARM-NEXT:    vld1.32 {d16}, [r0]!
; ARM-NEXT:    mov r2, #17
; ARM-NEXT:    vst1.32 {d16}, [r1]!
; ARM-NEXT:    vld1.32 {d16}, [r0]!
; ARM-NEXT:    vst1.32 {d16}, [r1]!
; ARM-NEXT:    vld1.32 {d16}, [r0]!
; ARM-NEXT:    mov r0, #42
; ARM-NEXT:    vst1.32 {d16}, [r1]!
; ARM-NEXT:    mov r1, #0
; ARM-NEXT:    bl consume_attributes
; ARM-NEXT:  .Ltmp11:
; ARM-NEXT:    add sp, sp, #24
; ARM-NEXT:    pop {r11, lr}
; ARM-NEXT:    add sp, sp, #16
; ARM-NEXT:    bx lr
;
; THUMB-LABEL: test_attributes:
; THUMB:       @ %bb.0: @ %entry
; THUMB-NEXT:    .pad #16
; THUMB-NEXT:    sub sp, #16
; THUMB-NEXT:    .save {r7, lr}
; THUMB-NEXT:    push {r7, lr}
; THUMB-NEXT:    .pad #24
; THUMB-NEXT:    sub sp, #24
; THUMB-NEXT:    add.w r12, sp, #32
; THUMB-NEXT:    stm.w r12, {r0, r1, r2, r3}
; THUMB-NEXT:    add r0, sp, #32
; THUMB-NEXT:    mov r1, sp
; THUMB-NEXT:    vld1.32 {d16}, [r0]!
; THUMB-NEXT:    movs r2, #17
; THUMB-NEXT:    vst1.32 {d16}, [r1]!
; THUMB-NEXT:    vld1.32 {d16}, [r0]!
; THUMB-NEXT:    vst1.32 {d16}, [r1]!
; THUMB-NEXT:    vld1.32 {d16}, [r0]!
; THUMB-NEXT:    movs r0, #42
; THUMB-NEXT:    vst1.32 {d16}, [r1]!
; THUMB-NEXT:    movs r1, #0
; THUMB-NEXT:    bl consume_attributes
; THUMB-NEXT:  .Ltmp11:
; THUMB-NEXT:    add sp, #24
; THUMB-NEXT:    pop.w {r7, lr}
; THUMB-NEXT:    add sp, #16
; THUMB-NEXT:    bx lr
entry:
; Check that arguments with attributes are lowered correctly.
; We call a function that has a nest argument and a byval argument.
  %statepoint_token = call token (i64, i32, ptr, i32, i32, ...) @llvm.experimental.gc.statepoint.p0(i64 0, i32 0, ptr elementtype(void (i32, ptr, i32, ptr)) @consume_attributes, i32 4, i32 0, i32 42, ptr nest null, i32 17, ptr byval(%struct2) %s, i32 0, i32 0)
  ret void
}

declare token @llvm.experimental.gc.statepoint.p0(i64, i32, ptr, i32, i32, ...)
declare i1 @llvm.experimental.gc.result.i1(token)
declare i32 @llvm.experimental.gc.result.i32(token)
declare ptr @llvm.experimental.gc.result.p0(token)
declare float @llvm.experimental.gc.result.f32(token)
declare double @llvm.experimental.gc.result.f64(token)
declare %struct @llvm.experimental.gc.result.struct(token)
declare ptr addrspace(1) @llvm.experimental.gc.relocate.p1(token, i32, i32)
