; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S -mtriple=armv7-unknown-linux-gnueabihf -passes='require<libcall-lowering-info>,atomic-expand' -codegen-opt-level=1 %s | FileCheck %s --check-prefix=V7
; RUN: opt -S -mtriple=armv8-unknown-linux-gnueabihf -passes='require<libcall-lowering-info>,atomic-expand' -codegen-opt-level=1 %s | FileCheck %s --check-prefix=V8

define i64 @atomicrmw_add_i64_as1(ptr addrspace(1) %p, i64 %v) {
; V7-LABEL: define i64 @atomicrmw_add_i64_as1(
; V7-SAME: ptr addrspace(1) [[P:%.*]], i64 [[V:%.*]]) {
; V7-NEXT:    call void @llvm.arm.dmb(i32 11)
; V7-NEXT:    br label %[[ATOMICRMW_START:.*]]
; V7:       [[ATOMICRMW_START]]:
; V7-NEXT:    [[LOHI:%.*]] = call { i32, i32 } @llvm.arm.ldrexd.p1(ptr addrspace(1) [[P]])
; V7-NEXT:    [[LO:%.*]] = extractvalue { i32, i32 } [[LOHI]], 0
; V7-NEXT:    [[HI:%.*]] = extractvalue { i32, i32 } [[LOHI]], 1
; V7-NEXT:    [[LO64:%.*]] = zext i32 [[LO]] to i64
; V7-NEXT:    [[HI64:%.*]] = zext i32 [[HI]] to i64
; V7-NEXT:    [[TMP1:%.*]] = shl i64 [[HI64]], 32
; V7-NEXT:    [[VAL64:%.*]] = or i64 [[LO64]], [[TMP1]]
; V7-NEXT:    [[NEW:%.*]] = add i64 [[VAL64]], [[V]]
; V7-NEXT:    [[LO1:%.*]] = trunc i64 [[NEW]] to i32
; V7-NEXT:    [[TMP2:%.*]] = lshr i64 [[NEW]], 32
; V7-NEXT:    [[HI2:%.*]] = trunc i64 [[TMP2]] to i32
; V7-NEXT:    [[TMP3:%.*]] = call i32 @llvm.arm.strexd.p1(i32 [[LO1]], i32 [[HI2]], ptr addrspace(1) [[P]])
; V7-NEXT:    [[TRYAGAIN:%.*]] = icmp ne i32 [[TMP3]], 0
; V7-NEXT:    br i1 [[TRYAGAIN]], label %[[ATOMICRMW_START]], label %[[ATOMICRMW_END:.*]]
; V7:       [[ATOMICRMW_END]]:
; V7-NEXT:    call void @llvm.arm.dmb(i32 11)
; V7-NEXT:    ret i64 [[VAL64]]
;
; V8-LABEL: define i64 @atomicrmw_add_i64_as1(
; V8-SAME: ptr addrspace(1) [[P:%.*]], i64 [[V:%.*]]) {
; V8-NEXT:    br label %[[ATOMICRMW_START:.*]]
; V8:       [[ATOMICRMW_START]]:
; V8-NEXT:    [[LOHI:%.*]] = call { i32, i32 } @llvm.arm.ldaexd.p1(ptr addrspace(1) [[P]])
; V8-NEXT:    [[LO:%.*]] = extractvalue { i32, i32 } [[LOHI]], 0
; V8-NEXT:    [[HI:%.*]] = extractvalue { i32, i32 } [[LOHI]], 1
; V8-NEXT:    [[LO64:%.*]] = zext i32 [[LO]] to i64
; V8-NEXT:    [[HI64:%.*]] = zext i32 [[HI]] to i64
; V8-NEXT:    [[TMP1:%.*]] = shl i64 [[HI64]], 32
; V8-NEXT:    [[VAL64:%.*]] = or i64 [[LO64]], [[TMP1]]
; V8-NEXT:    [[NEW:%.*]] = add i64 [[VAL64]], [[V]]
; V8-NEXT:    [[LO1:%.*]] = trunc i64 [[NEW]] to i32
; V8-NEXT:    [[TMP2:%.*]] = lshr i64 [[NEW]], 32
; V8-NEXT:    [[HI2:%.*]] = trunc i64 [[TMP2]] to i32
; V8-NEXT:    [[TMP3:%.*]] = call i32 @llvm.arm.stlexd.p1(i32 [[LO1]], i32 [[HI2]], ptr addrspace(1) [[P]])
; V8-NEXT:    [[TRYAGAIN:%.*]] = icmp ne i32 [[TMP3]], 0
; V8-NEXT:    br i1 [[TRYAGAIN]], label %[[ATOMICRMW_START]], label %[[ATOMICRMW_END:.*]]
; V8:       [[ATOMICRMW_END]]:
; V8-NEXT:    ret i64 [[VAL64]]
;
  %r = atomicrmw add ptr addrspace(1) %p, i64 %v seq_cst
  ret i64 %r
}
